### ISSUE TITLE
Screenshots in the README?

### ISSUE THREAD

**Issue by neuromancer** [joetsoi/OpenMoonstone#5]
I think people will be more interested in testing this re-implementation and maybe collaborate with some code if you show the current state of this port in the README. It is great that you included a Youtube link with gameplay, you don't need to remove it!, but adding screenshots could make a bigger impact if you check this project for the first time.

**Comment by joetsoi** [comment]
That's a good point! There's a bunch of stuff that needs improvement to move it from "casual side project 1 person hacks on" to a state where multiple people can contribute.

Screenshots and some form of progress/current state would be a good start.
